Blog app - Views and Navigations
Enoisong/blog_app pull request #6
Opened 2023-08-31 19:03 UTC by Enoisong

## In this milestone, I implement the Views associated with the Blog App Models and Controllers 👩‍💻

## Requirements:
-  Implement the design from the sneak peek wireframes.🐚✏
-  Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone) 🏃‍♂️🏃‍♂️
      -  **Note**: Analyze the wireframes deeply and try to identify all the necessary elements and how a user would navigate from one page to another✔📄
-  Use methods already created in the [Blog App - processing data in models]🐚🤸‍♂️
(https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
      -  **Hint**: In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).✍🤸‍♂️

## Achievements

- Add views for each controller as per the wireframe ✍🤸‍♂️
- Add Navigations✔📄
- Update rspec✏
- Add style🐚
- Fix Linters.⛏

2023-08-31 19:35 UTC, VICTOR-CHUKWU requested changes
Hi @Enoisong  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed
- views not fitting perfectly yet


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 19:35 UTC, VICTOR-CHUKWU commented on app/views/shared/_user-container.html.erb
> +  </div>
- [ ] kindly keep to design wireframe, even after adding user photo in the seed file, I still could not see the picture added, kindly fix
your design :point_down: 
![Screenshot from 2023-08-31 20-24-55](https://github.com/Enoisong/blog_app/assets/66097371/3fef6f0c-f89e-49ed-a64e-67f52ad4d21e)
wireframe :point_down: 
![Screenshot from 2023-07-20 22-19-45](https://github.com/Enoisong/blog_app/assets/66097371/ee9ff3c5-5a18-47e4-8154-1032e8258b8b)

2023-08-31 19:35 UTC, VICTOR-CHUKWU commented on app/views/users/show.html.erb
> +</div>
- [ ] also kindly keep to the given wireframe 
your design :point_down: 
![Screenshot from 2023-08-31 20-31-01](https://github.com/Enoisong/blog_app/assets/66097371/8a3a2e83-ca6b-4349-881e-12a8272c041a)
design guide :point_down: 
![Screenshot from 2023-07-20 22-23-13](https://github.com/Enoisong/blog_app/assets/66097371/9aa92755-a33e-44a4-b60b-1a46cbd2e8f6)

2023-08-31 19:35 UTC, VICTOR-CHUKWU commented on app/views/posts/index.html.erb
> +        <h3><%= link_to post.title, user_post_url(@user, post) %></h3>
- [ ] also the profile picture is not showing, kindly fix it as to fit the wireframe

2023-09-01 01:53 UTC, Enoisong commented
## Required Changes Implementation👨‍💻

## Requirements

-  The profile picture is not showing, kindly fix it as to fit the wireframe.

-  Kindly keep to design wireframe, even after adding user photo in the seed file, I still could not see the picture added, kindly fix.

- kindly keep to the given wireframe.
 
## Achievements
Add profile picture to the app with alt image (profile)✔

All Implementations of the design follows the sneak peak wireframes✔

2023-09-01 02:11 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Enoisong 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- Now the User picture is showing :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 02:16 UTC, merged