Add devise
Enoisong/blog_app pull request #9
Opened 2023-09-06 18:07 UTC by Enoisong

Dear Reviewer,

In this PR we have done the following👨‍💻👨‍💻

## Requirements
-  Remove current_user method in ApplicationController🤸‍♂️🤸‍♂️
-  [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
    -   Can register a new user✏
    -   User logs in with a combination of email and password.🗝
    -   Hashed password should be stored in the database.🐚🐚
    -   Ask for confirmation of email.🧍‍♂️
    -   Can reset password🗝
[Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and  styling.🤸‍♂️🤸‍♂️

## Achievements
-  Remove current_user method in ApplicationController🤸‍♂️✅
-  [Install and setup devise](https://github.com/heartcombo/devise#getting-started)🐚✅
    -   Can register a new user✏
    -   User logs in with a combination of email and password.🗝
    -   Hashed password should be stored in the database.🐚🐚
    -   Ask for confirmation of email.🧍‍♂️
    -   Can reset password🗝
[Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and  styling.🤸‍♂️✅

2023-09-06 18:35 UTC, VICTOR-CHUKWU requested changes
Hi @Enoisong  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- devise correctly installed and used


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 18:35 UTC, VICTOR-CHUKWU commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] kindly allow the user to confirm his/her email while registering by adding confirmable :+1:

2023-09-06 18:35 UTC, VICTOR-CHUKWU commented on app/views/devise/sessions/new.html.erb
> +<% end %>
- [ ] kindly make your design match the wireframe
your design :point_down: 
![image](https://github.com/Enoisong/blog_app/assets/66097371/61f83f26-de76-4e2a-bf53-84a308da291f)
wireframe given :point_down: 
![Screenshot from 2023-09-06 19-26-16](https://github.com/Enoisong/blog_app/assets/66097371/0ed175c8-551c-49d6-aed6-ad210af8e5a2)

2023-09-07 09:16 UTC, Enoisong commented
## Required Changes Implementation👨‍💻👨‍💻

## Requirements
-   kindly allow the user to confirm his/her email while registering by adding confirmable 👍
-   kindly make your design match the wireframe
 

## Achievements

Add `confirmable` that allows the user to confirm his/her email while registering.💯✔

All Implementations of the design matches the `sneak peak` wireframes💯✔

2023-09-07 09:28 UTC, mikethreels approved these changes
Hi Enobong, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job following the instructions of the previous CR.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 09:34 UTC, merged